"use strict";

var CONFIG_OPTIONS = {
  CONFIG_LANGUAGES: [
    ["en-us",     "English"],
    ["zh-cn",     "简体中文"],
    ["zh-tw",     "繁體中文"],
  ],
  CONFIG_VERSIONS: [
    ["latest",    "Development"],
    ["stable",    "Stable Release"],
    ["0.27",      "Release 0.27"],
    ["0.26",      "Release 0.26"],
    ["0.25",      "Release 0.25"],
    ["0.24",      "Release 0.24"],
    ["0.23",      "Release 0.23"],
    ["0.22",      "Release 0.22"],
    ["0.21",      "Release 0.21"],
    ["0.20",      "Release 0.20"],
    ["0.19",      "Release 0.19"],
    ["0.18",      "Release 0.18"],
    ["0.17",      "Release 0.17"],
    ["0.16",      "Release 0.16"],
    ["0.15",      "Release 0.15"],
    ["0.14",      "Release 0.14"],
    ["0.13",      "Release 0.13"],
    ["0.12",      "Release 0.12"],
    ["0.11",      "Release 0.11"],
    ["0.10",      "Release 0.10"],
    ["0.9",       "Release 0.9"],
    ["0.8",       "Release 0.8"],
    ["0.7",       "Release 0.7"],
    ["0.6",       "Release 0.6"],
    ["0.5",       "Release 0.5"],
    ["0.4",       "Release 0.4"],
    ["0.3",       "Release 0.3"],
    ["0.2",       "Release 0.2"],
    ["0.1",       "Release 0.1"],
  ],
  CONFIG_PROJECTS: [
    ["Index",     "https://projects.localizethedocs.org"],
    ["Crowdin",   "https://localizethedocs.crowdin.com/pyo3-guide-l10n"],
    ["GitHub",    "https://github.com/localizethedocs/pyo3-guide-l10n"],
    ["AtomGit",   "https://atomgit.com/localizethedocs/pyo3-guide-l10n"],
    ["GitFlic",   "https://gitflic.ru/project/localizethedocs/pyo3-guide-l10n"],
  ]
};
